resolver: lts-9.21

packages:
  - .

extra-deps:
  - gloss-1.12.0.0
  - gloss-rendering-1.12.0.0
  - grenade-0.1.0
  - hmidi-0.2.2.1
  - hosc-0.16
  - hsc3-0.16
  - hsc3-process-0.10.0
  - tidal-0.9.9
